# Generated by Django 2.2.3 on 2019-08-09 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190809_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
