# Generated by Django 2.2.3 on 2019-08-09 02:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20190809_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 2, 52, 57, 709938, tzinfo=utc)),
        ),
    ]
